// This file is auto-generated by scripts/generate-gallery-data.js
// Do not edit manually.

export interface GalleryItem {
  src: string;
  type: "photo" | "video";
}

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    "src": "/media/galeri/musteri/IMG_1790.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/IMG_2110.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/IMG_5940.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/IMG_5941.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/IMG_5942.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/IMG_5943.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/IMG_5944.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/IMG_5945.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/IMG_5949.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/IMG_6343.MOV",
    "type": "video"
  },
  {
    "src": "/media/galeri/musteri/photo_5222318759358437776_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5222318759358437777_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5222318759358437778_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5222318759358437779_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5262867644384221458_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5262867644384221459_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5262867644384221460_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5262867644384221461_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5269626677367609507_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5269626677367609508_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5269626677367609509_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5296399832748596372_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5296399832748596373_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5296399832748596374_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5296399832748596375_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242723_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242724_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242725_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242726_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242727_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242728_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242729_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242730_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242731_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242732_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242733_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242734_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242783_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242784_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242785_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242787_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242788_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242789_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625242790_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625243025_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625243026_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625243027_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625243028_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625243029_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625243030_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5350437354625243031_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453388_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453389_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453390_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453391_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453392_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453393_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453394_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453395_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453396_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453397_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453398_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453399_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453400_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453401_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453403_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453404_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453405_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453406_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453407_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453408_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453409_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453410_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453411_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453412_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453413_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453414_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453415_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453416_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5399944888595453417_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5445155157462161177_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5445155157462161178_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5445155157462161179_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5445155157462161180_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5445155157462161181_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5445155157462161182_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5445155157462161183_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5445155157462161184_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5445155157462161185_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771790740332678919_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771790740332678920_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771790740332678921_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771790740332678922_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589902_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589903_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589904_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589906_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589907_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589908_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589909_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589910_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589911_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589912_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5771851557069589913_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5774042540146363854_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5774042540146363855_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5774042540146363856_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5774042540146363857_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782169_y.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782170_y.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782171_y.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782172_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782173_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782174_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782175_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782176_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782177_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5778211377137782178_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5780463176951467401_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5780463176951467402_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5780463176951467403_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5780463176951467404_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5780463176951467405_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5780749835953705544_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5780749835953705545_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5780749835953705546_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5780749835953705547_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583343_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583344_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583345_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583346_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583347_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583348_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583349_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583350_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583351_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583352_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583353_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583355_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583356_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583357_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583446_y.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583447_y.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5787249693430583450_y.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5796694253500042981_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5796694253500042982_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5796694253500042983_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5796694253500042984_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5796694253500042985_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5800876310400798150_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5800876310400798151_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5800876310400798152_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5800876310400798153_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5800876310400798154_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5800876310400798155_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5800876310400798156_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5800876310400798157_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5800876310400798158_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5805194698153464026_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5805194698153464027_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5805194698153464028_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5805194698153464029_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5805194698153464031_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5805194698153464032_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5805194698153464033_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5805194698153464034_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5809643648616959610_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5809643648616959611_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5809643648616959612_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5809643648616959613_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629465_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629467_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629468_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629469_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629470_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629471_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629472_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629473_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629474_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629475_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629476_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629477_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629478_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629479_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629480_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629481_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629482_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5845771899898629483_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5848131056714845712_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5848131056714845713_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5848131056714845714_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5848131056714845715_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5848131056714845716_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5854863972002106915_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5854863972002106916_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5854863972002106917_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5854863972002106918_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5854863972002106919_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465479_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465480_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465481_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465482_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465483_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465484_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465485_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465486_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465487_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465488_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465489_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465490_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465491_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465492_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465493_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465494_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465495_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465496_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465498_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465500_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465501_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465502_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5866003077058465503_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5872860529217441550_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5872860529217441551_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5872860529217441552_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5872860529217441553_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105562_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105563_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105564_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105565_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105566_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105567_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105568_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105569_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105570_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105731_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105732_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105733_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105734_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5875222516417105735_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5881890002172579320_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5881890002172579321_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5881890002172579322_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5881890002172579323_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5881890002172579351_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5881890002172579352_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5881890002172579353_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5881890002172579354_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5893451229499690967_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5893451229499690968_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5893451229499690969_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5893451229499690970_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5893451229499690971_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165681_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165682_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165683_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165684_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165685_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165686_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165687_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165688_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165689_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165690_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165691_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165692_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5906683564177165693_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5913595644025179581_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5913595644025179582_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5913595644025179583_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5913595644025179584_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5918175303228395302_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5918175303228395303_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5918175303228395304_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5918175303228395305_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5918175303228395306_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5924942011318341280_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5924942011318341281_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5924942011318341282_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5924942011318341283_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5924942011318341284_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5924942011318341285_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5924942011318341286_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5924942011318341287_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5927193811132026744_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5927193811132026745_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5927193811132026746_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5927193811132026747_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5927193811132026748_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5927193811132026749_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993938_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993939_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993940_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993941_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993942_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993943_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993944_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993945_y.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993946_y.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993947_y.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993948_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993949_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993950_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993951_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993952_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993953_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_5949742393730993954_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6015060402397449564_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6015060402397449565_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6015060402397449566_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6015060402397449567_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6015060402397449568_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6028468658935369350_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6028468658935369351_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6028468658935369352_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6028468658935369353_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6028468658935369354_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6028468658935369355_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6028468658935369356_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6030412024262626515_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6030412024262626516_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6030412024262626517_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6030412024262626518_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6030412024262626519_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6030412024262626520_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6030412024262626521_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6037407950462193358_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6037407950462193359_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6037407950462193360_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6037407950462193397_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6037407950462193398_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6037407950462193399_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768644_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768645_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768646_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768647_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768648_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768649_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768670_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768671_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768672_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6039562318942768673_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652074_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652075_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652076_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652125_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652126_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652127_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652129_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652130_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652131_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652132_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652133_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652134_w.webp",
    "type": "photo"
  },
  {
    "src": "/media/galeri/musteri/photo_6048734054099652135_w.webp",
    "type": "photo"
  }
];
